[package]
name = "homework_of_ch3"
version = "0.1.0"
authors = ["aver85 <aver803r803bath261@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
